### ISSUE TITLE
Bearings missing in BOM

### ISSUE THREAD

**Issue by Jerzeek** [ONEARMY/precious-plastic-starterkit-injection#1]
precious-plastic-starterkit-injection/3. Build the machines/1. Shredder/Bill-of-Materials-Shredder.pdf

The BOM pdf is missing the UCFL204 20mm bearings (2x)

**Comment by davehakkens** [comment]
huh in shredder or injection?

**Comment by Jerzeek** [comment]
It is missing the bearings used in the shredder, but it is in the starterkit of a injection workspace 😉
(Read: Probably also missing in the big starterkit and the mix starterkit)

**Comment by davehakkens** [comment]
Will be fixed in release 1.0.1
